= .NET Observability App
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2023-08
// Metadata
:description: This is just an example app that tries to showcase the same features as the main repo (quarkus-observability-app), but using .NET
:keywords: openshift, Python, logging, metrics, tracing, red hat
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 3
:sectnums: 
:source-highlighter: pygments
:imagesdir: docs/images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// Icons for GitHub
:yes: :heavy_check_mark:
:no: :x:
endif::[]
ifndef::env-github[]
:icons: font
// Icons not for GitHub
:yes: icon:check[]
:no: icon:times[]
endif::[]

// Create the Table of contents here
toc::[]


== Introduction

This is just an example app that tries to showcase the same features as the main repo (quarkus-observability-app), but using .NET

WARNING: Please, go to the main repository to get how to configure all the Observability components for Openshift: https://github.com/alvarolop/quarkus-observability-app

This example creates an ASP.NET Core web application that responds to HTTP requests, with customizable /hello messages, error handling, and health endpoints, including readiness and liveness checks. It also exposes Prometheus metrics in the `/metrics` endpoint.




=== Endpoints

* `/`: This endpoint returns "Welcome to our .NET application, Alvaro!" and simulates some processing time. It is instrumented with Prometheus metrics.
* `/error`: This endpoint raises an exception to simulate an error scenario and is also instrumented with Prometheus metrics.


=== Accessing Prometheus Metrics

The Prometheus metrics endpoint is accessible at `http://localhost:8080/metrics` when the application is running. Prometheus can scrape and store these metrics for monitoring purposes.

We define several Prometheus metrics: REQUEST_COUNTER, REQUEST_DURATION, ERROR_COUNTER, and CURRENT_REQUESTS. When a request is made to the '/' endpoint, the REQUEST_COUNTER is incremented, and the REQUEST_DURATION measures the time taken to process the request. When the '/error' endpoint is accessed, the ERROR_COUNTER is incremented. The CURRENT_REQUESTS metric is a gauge that represents the number of active requests at any given time.




== Run it! Locally

[NOTE]
====
install the .NET 7.0 tools with the following command:

[source, bash]
----
sudo dnf install dotnet-sdk-7.0
----

====

Install the required .NET dependencies using dotnet:

[source, bash]
----
dotnet restore
----

To run the .NET app with Prometheus metrics, first, compile the application and then run it using the following commands:

[source, bash]
----
dotnet build
dotnet run
----

This will start the app on port 8080, and Prometheus metrics will be available on port 8080/metrics.



== Run it! Podman

You can also run the application using Docker. First, you have to publish the application:

[source, bash]
----
dotnet publish HelloWorldApp/ -f net7.0 -c Release
----


Build the Docker image with the following command:

[source, bash]
----
podman build -t quay.io/alopezme/dotnet-observability-app:latest .
----

Replace `dotnet-observability-app` with the desired name for your Docker image.

To start the app as a container, use the following command:

[source, bash]
----
podman run -p 8080:8080 -e GREETINGS_NAME=Alvaro quay.io/alopezme/dotnet-observability-app:latest
----


== Run it! Openshift

You can also push this image to a container registry and later use it from Openshift:

[source, bash]
----
podman push quay.io/alopezme/dotnet-observability-app:latest
----

Deploy the app on Openshift:

[source, bash]
----
oc process -f openshift/app.yaml | oc apply -f -
oc process -f openshift/service-monitor.yaml | oc apply -f -
----

NOTE: If you face issues creating and configuring the Service monitor, you can use this https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/troubleshooting.md[Thoubleshooting guide].


== License

This project is licensed under the GNU General Public License (GPL) version 3.0 - see the link:./LICENSE[LICENSE] file for details.

Feel free to explore and modify the app as needed. If you have any questions or suggestions, please open an issue or submit a pull request!

Let's keep monitoring and improving together! 
